version: "2"

services:

  ### build tool jenkins
  jenkins:
    build:
      context: jenkins
      dockerfile: Dockerfile
    ports:
      - 49001:8080
    hostname: jenkins
    volumes_from:
      - data

  ### store files
  data:
    image: busybox
    volumes:
      - ~/jenkins:/var/jenkins_home
      - ~/.ssh:/var/jenkins_home/.ssh
      - ~/.aws:/var/jenkins_home/.aws