
- hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: true
  pre_tasks:
    - name: install python2
      raw: sudo apt-get -y install python-simplejson

  tasks:
    - name: Install prerequisites
      apt:
        name: ['apt-transport-https','ca-certificates','curl','gnupg-agent','software-properties-common']
        update_cache: yes

    - name: Add Docker GPG key
      become: yes
      shell: curl -s https://download.docker.com/linux/ubuntu/gpg | apt-key add -

    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable

    - name: Install Docker
      apt:
        name: docker-ce
